### ISSUE TITLE
Error in eval(inherit, parent_env, NULL) :    object 'OptimInstanceSingleCrit' not found

### ISSUE THREAD

**Issue by cmululu** [mlr-org/mlr3fselect#101]
After I have upgraded the 'bbotk' to version 0.8.0.9000 and the 'mlr3fselect' to version 0.12.0.9000,  the error will occur when i run the example codes.

`library("mlr3verse")
library('mlr3fselect')

tsk("spam")

instance = fsi(
  task = tsk("spam"),
  learner = lrn("classif.svm", type = "C-classification"),
  resampling = rsmp("cv", folds = 3),
  measures = msr("classif.ce"),
  terminator = trm("evals", n_evals = 20)
)
`
Error in eval(inherit, parent_env, NULL) : 
  object 'OptimInstanceSingleCrit' not found

I have tried to downgrade 'bbotk' to version 0.8.0 and 'mlr3fselect' to 0.12.0 both and solely, but the error remains.

**Comment by cmululu** [comment]
Just downgrading 'bbotk' to version 0.8.0 and keeping 'mlr3fselect' to version 0.12.0.9000 now works.

**Comment by be-marc** [comment]
Yes we are doing a major refactoring. Sorry that it caused you problems. The CRAN versions should work together and now the dev version from github but not mixed.
