### ISSUE TITLE
CRAN failure

### ISSUE THREAD

**Issue by hadley** [mlr-org/mlr3fselect#125]
Unfortunately the recent waldo release broke your package on CRAN because it no longer imports tibble, and your package was implicitly depending on it. The easiest fix is to just make the dependency explicit, by adding tibble to Suggests.

Many apologies for the hassle. Unfortunately we didn't discover this prior to CRAN release because we had a bug in the code that runs our revdep checks 🙁.

**Comment by be-marc** [comment]
Looks like the `vctrs` package is missing and not tibble? The `expect_vector` function fails with waldo 0.6.0

**Comment by be-marc** [comment]
Fixed by dfad3d5d856ce4a90fa8c84780069c1a732cd064

**Comment by hadley** [comment]
Doh, yes, sorry.
