### ISSUE TITLE
Supported learners in AutoFSelector

### ISSUE THREAD

**Issue by MislavSag** [mlr-org/mlr3fselect#31]
How do I know which learners can be used as an argument to `AutoFSelector`. 

In the documentation it says:
```
learner    (mlr3::Learner) Learner to optimize the feature subset for, see FSelectInstanceSingleCrit.
```
but I am not sure if that includes mlr3extralearners or just learners.

**Comment by be-marc** [comment]
Of course you can use the learners provided by the `mlr3extralearners` package. `(mlr3::Learner)` just means that you have to pass an object of class `Learner`. `mlr3` and `mlr3extralearners` provide learners that inherit from this class.
