### ISSUE TITLE
Error in initialize(...) : unused argument (store_x_domain = FALSE)

### ISSUE THREAD

**Issue by nipnipj** [mlr-org/mlr3fselect#42]
I'm getting `Error in initialize(...) : unused argument (store_x_domain = FALSE)` when trying to run this example https://mlr3fselect.mlr-org.com/reference/FSelectorExhaustiveSearch.html

**Comment by be-marc** [comment]
Thanks for reporting. Bug occurs with `bbotk` devel version. Fixed with #43.
